/**
 * Created by ajith on 31/10/18.
 */

public class NES_EnrollmentCompHandler {

  /*  NES_EnrollmentCompBusinessLogic logicHandler = new NES_EnrollmentCompBusinessLogic();

    public void handleBeforeInsert(List<Enrollment_Component__c> newList){

    }

    public void handleBeforeUpdate(Map<Id, Enrollment_Component__c> oldMap, Map<Id, Enrollment_Component__c> newMap){
       logicHandler.ECCompletionCheck(newMap, oldMap);
    }
*/
   /* public void handleAfterInsert(List<Enrollment_Component__c> newList){

    }

    public void handleAfterUpdate(Map<Id, Enrollment_Component__c> oldMap, Map<Id, Enrollment_Component__c> newMap){

    }*/

}