/**
 * Created by rdehler 12/16/18
 * Constants for the NES application
 */
public with sharing class NES_Constants {
	public static final String ECA_STATUS_COMPLETED = 'Complete';
    
    public static final String EC_RECORDTYPE_STAGE = 'Stage';
    
    public static final String DOCUMENT_AUTHORIZATION_CT = 'Caretaker';
    
    public static final String COMMUNITY_NAME = 'OBL Enroll';

    public static final String PE_STATUS_COMPLETE = 'Complete';

    public static Boolean runAssignment = true;
}