/**
 *  @author: Ali KM (Ness Tech)
 *  @Created on: 04/07/2020
 *  @User Story: 
    @Purpose: This class handles following 
        -> 
        -> 
    @Usage: 
        
 */
public class programExportFormat {
    /**
     *  @ALIKM 20/apr/2020- commenting out changes

        public Id sourceID {get; set;}
    
        public Integer version {get; set;}
        
        public ecrNode root {get; set;}
    
        public Integer steps {get; set;}
    
        public Integer countECs {get; set;}
    
        public Set<String> ecTypes {get; set;} 
    
        public programExportFormat() {
            this.steps = 0;
            this.countECs = 0;
            this.version = 0;
            this.ecTypes = new Set<String>();
        }
    
        public programExportFormat(ecrNode root) {
            this();
            this.root = root;
        }
    */

}