@isTest(SeeAllData=false isParallel=true)
public class QueueTest {
    /**
        @isTest static void testMethod1() 
        {
            Queue q = new Queue();
            q.enqueue(Id.valueOf('a0f0n000001VAoJAAW'));
            q.enqueue(Id.valueof('a0f0n000001IAQ2AAO'));
            System.debug('queue size:' + q.size());
            System.debug('front element is:' + q.peek());
            q.dequeue();
            q.dequeue();
            if (q.isEmpty()) {
                System.debug('queue is empty..');
            } else {
                System.debug('queue is NOT empty..');
            }
            q.peek();
        }
    */
}