/**
 * Template from: https://www.techiedelight.com/queue-implementation-in-java/
 */
global class Queue {
    
    /**
	 * 	@ALIKM 20/apr/2020- commenting out changes

        private List<String> members;
    
        public Queue() {
            members = new List<String>();
        }
    
        public String dequeue() {
            if (isEmpty()) {
                System.debug('Underflow, program terminated.');
                return null;
            }
            System.debug('Removing::' + members.get(0));
            return members.remove(0);
        }
    
        public void enqueue(String member) {
            System.debug('Inserting::' + member);
            members.add(member);
        }
    
        public String peek(){
            if (isEmpty()) {
                System.debug('Underflow, program terminated.');
                return null;
            }
            return members.get(0);
        }
    
        public Integer size() {
            return members.size();
        }
    
        public Boolean isEmpty() {
            return (members.size()==0);
        }

	*/

}